// Ontario Dealers — Multi-Make
// Sorted within each make from largest to smallest

const MAKES = [
  { id: "ford",       label: "Ford",       color: "#003478" },
  { id: "toyota",     label: "Toyota",     color: "#eb0a1e" },
  { id: "honda",      label: "Honda",      color: "#cc0000" },
  { id: "chevrolet",  label: "Chevrolet",  color: "#c8a84b" },
  { id: "hyundai",    label: "Hyundai",    color: "#002c5f" },
  { id: "kia",        label: "Kia",        color: "#05141f" },
  { id: "nissan",     label: "Nissan",     color: "#c3002f" },
  { id: "subaru",     label: "Subaru",     color: "#1a3a6e" },
  { id: "jeep",       label: "Jeep",       color: "#2a6d1f" },
  { id: "ram",        label: "Ram",        color: "#1a1a1a" },
];

const DEALERS = [

  // ══════════════════ FORD ══════════════════
  {
    id: 1, make: "ford",
    name: "East Court Ford Lincoln",
    city: "Scarborough",
    region: "toronto-gta", size: "large",
    website: "https://www.eastcourtfordlincoln.com",
    phone: "(416) 261-6200",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "Largest Ford dealer in Canada by volume. Full Bronco & F-150 inventory.",
  },
  {
    id: 2, make: "ford",
    name: "Yonge-Steeles Ford Lincoln",
    city: "Toronto", region: "toronto-gta", size: "large",
    website: "https://www.yongesteelesfordlincoln.com",
    phone: "(416) 222-5544",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Large inventory. Competitive pricing on trucks & SUVs.",
  },
  {
    id: 3, make: "ford",
    name: "Erinwood Ford",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.erinwoodford.com",
    phone: "(905) 826-1100",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "Top-rated dealer in GTA. Wide Bronco Sasquatch selection.",
  },
  {
    id: 4, make: "ford",
    name: "Planet Ford",
    city: "Brampton", region: "toronto-gta", size: "large",
    website: "https://www.planetford.ca",
    phone: "(905) 453-6080",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "Huge lot with strong Bronco & truck inventory.",
  },
  {
    id: 5, make: "ford",
    name: "Thorncrest Ford",
    city: "Etobicoke", region: "toronto-gta", size: "large",
    website: "https://www.thorncrestford.ca",
    phone: "(416) 622-3441",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Well-established GTA dealer with strong service department.",
  },
  {
    id: 6, make: "ford",
    name: "Downtown Ford",
    city: "Toronto", region: "toronto-gta", size: "medium",
    website: "https://www.downtownford.ca",
    phone: "(416) 364-6600",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Urban dealership in central Toronto.",
  },
  {
    id: 7, make: "ford",
    name: "Courtesy Ford Lincoln",
    city: "London", region: "london", size: "large",
    website: "https://www.courtesyford.com",
    phone: "(519) 455-6280",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Close to Windsor (2 hrs). Known for competitive B-level deals.",
  },
  {
    id: 8, make: "ford",
    name: "Barrie Ford",
    city: "Barrie", region: "barrie", size: "large",
    website: "https://www.barrieford.com",
    phone: "(705) 726-9888",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "High-volume dealer north of GTA.",
  },
  {
    id: 9, make: "ford",
    name: "Rose City Ford",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.rosecityford.com",
    phone: "(519) 966-3673",
    hasZeroPercent: false, islamicFriendly: true,
    notes: "Local Windsor dealer. Will price-match GTA offers for Ford employees.",
  },
  {
    id: 10, make: "ford",
    name: "Performance Ford",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.performancefordwindsor.com",
    phone: "(519) 944-4600",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Second Windsor option. Good for test drives.",
  },
  {
    id: 11, make: "ford",
    name: "Ken Knapp Ford",
    city: "Essex", region: "windsor", size: "small",
    website: "https://www.kenknappford.com",
    phone: "(519) 776-6481",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Small town dealer just east of Windsor. Personal service.",
  },
  {
    id: 12, make: "ford",
    name: "Lally Ford",
    city: "Tilbury", region: "windsor", size: "small",
    website: "https://www.lallyford.com",
    phone: "(519) 682-0444",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Known for customization options.",
  },
  {
    id: 13, make: "ford",
    name: "Watford Ford",
    city: "Watford", region: "other", size: "small",
    website: "https://www.watfordford.com",
    phone: "(519) 876-2264",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Rural dealer, often flexible on price to attract city buyers.",
  },
  {
    id: 14, make: "ford",
    name: "Mt. Brydges Ford",
    city: "Mount Brydges", region: "other", size: "small",
    website: "https://www.mtbford.ca",
    phone: "(519) 264-9171",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "No-pressure, commission-free sales model.",
  },
  {
    id: 15, make: "ford",
    name: "Barber Ford",
    city: "Alliston", region: "barrie", size: "small",
    website: "https://www.barberford.ca",
    phone: "(705) 435-3337",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Active in the employee A-Plan deal community.",
  },

  // ══════════════════ TOYOTA ══════════════════
  {
    id: 100, make: "toyota",
    name: "Toronto Toyota",
    city: "Toronto", region: "toronto-gta", size: "large",
    website: "https://www.torontotoyota.com",
    phone: "(416) 285-7200",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "One of Toronto's highest-volume Toyota dealers. Great 4Runner & Tacoma stock.",
  },
  {
    id: 101, make: "toyota",
    name: "Mississauga Toyota",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.mississaugatoyota.com",
    phone: "(905) 279-1111",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "Large GTA dealer. Strong off-road lineup (4Runner TRD, Tacoma).",
  },
  {
    id: 102, make: "toyota",
    name: "Brampton Toyota",
    city: "Brampton", region: "toronto-gta", size: "large",
    website: "https://www.bramptontoyota.com",
    phone: "(905) 451-5777",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "High volume dealer. Popular with Brampton/Mississauga community.",
  },
  {
    id: 103, make: "toyota",
    name: "Scarborough Toyota",
    city: "Scarborough", region: "toronto-gta", size: "large",
    website: "https://www.scarboroughtoyota.com",
    phone: "(416) 438-3355",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "One of the oldest Toyota dealers in the GTA.",
  },
  {
    id: 104, make: "toyota",
    name: "Etobicoke Toyota",
    city: "Etobicoke", region: "toronto-gta", size: "medium",
    website: "https://www.etobicoke-toyota.ca",
    phone: "(416) 231-6611",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Solid west-end GTA option with good service reviews.",
  },
  {
    id: 105, make: "toyota",
    name: "Courtesy Toyota",
    city: "London", region: "london", size: "large",
    website: "https://www.courtesytoyota.ca",
    phone: "(519) 455-7777",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "London's largest Toyota dealer. Good for SW Ontario buyers.",
  },
  {
    id: 106, make: "toyota",
    name: "Windsor Toyota",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.windsortoyota.com",
    phone: "(519) 945-6363",
    hasZeroPercent: false, islamicFriendly: true,
    notes: "Local Windsor option. Friendly to employee referrals.",
  },
  {
    id: 107, make: "toyota",
    name: "Barrie Toyota",
    city: "Barrie", region: "barrie", size: "medium",
    website: "https://www.barrietoyota.com",
    phone: "(705) 726-7561",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Serves Barrie and Simcoe County.",
  },

  // ══════════════════ HONDA ══════════════════
  {
    id: 200, make: "honda",
    name: "Parkway Honda",
    city: "Toronto", region: "toronto-gta", size: "large",
    website: "https://www.parkwayhonda.com",
    phone: "(416) 494-5000",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Top-volume Honda dealer in Ontario. Pilot, Ridgeline, CR-V in stock.",
  },
  {
    id: 201, make: "honda",
    name: "Downtown Honda",
    city: "Toronto", region: "toronto-gta", size: "large",
    website: "https://www.downtownhonda.com",
    phone: "(416) 924-5000",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Prime downtown location with a wide new-car inventory.",
  },
  {
    id: 202, make: "honda",
    name: "Mississauga Honda",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.mississaugahonda.com",
    phone: "(905) 279-8877",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "Large dealer, competitive trade-in values and 0% promos.",
  },
  {
    id: 203, make: "honda",
    name: "Honda Brampton",
    city: "Brampton", region: "toronto-gta", size: "large",
    website: "https://www.hondabrampton.com",
    phone: "(905) 460-1100",
    hasZeroPercent: false, islamicFriendly: true,
    notes: "High-demand area dealer. Good for CR-V and Pilot.",
  },
  {
    id: 204, make: "honda",
    name: "Harmony Honda",
    city: "Oshawa", region: "other", size: "medium",
    website: "https://www.harmonyhonda.com",
    phone: "(905) 436-3000",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "East GTA, known for no-pressure sales experience.",
  },
  {
    id: 205, make: "honda",
    name: "Windsor Honda",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.windsorhonda.com",
    phone: "(519) 258-8286",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Local Windsor Honda dealer.",
  },

  // ══════════════════ CHEVROLET ══════════════════
  {
    id: 300, make: "chevrolet",
    name: "Budds' Chevrolet Cadillac Buick GMC",
    city: "Oakville", region: "toronto-gta", size: "large",
    website: "https://www.buddschevy.com",
    phone: "(905) 845-3631",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Award-winning GMC/Chevy dealer. Silverado, Colorado, Tahoe stock.",
  },
  {
    id: 301, make: "chevrolet",
    name: "Humberview Chevrolet",
    city: "Toronto", region: "toronto-gta", size: "large",
    website: "https://www.humberviewchevrolet.com",
    phone: "(416) 247-3381",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Large GTA Chevy presence. Competitive on Silverado fleet deals.",
  },
  {
    id: 302, make: "chevrolet",
    name: "Performance Chevrolet Buick GMC",
    city: "Brampton", region: "toronto-gta", size: "large",
    website: "https://www.performancechevy.ca",
    phone: "(905) 454-1511",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "One of GTA's highest-volume GM dealerships.",
  },
  {
    id: 303, make: "chevrolet",
    name: "Courtesy Chevrolet Cadillac",
    city: "London", region: "london", size: "large",
    website: "https://www.courtesychev.com",
    phone: "(519) 455-5560",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Large London dealer. Traverse, Blazer, Equinox in stock.",
  },
  {
    id: 304, make: "chevrolet",
    name: "Windsor Chevrolet Buick GMC",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.windsorchevy.ca",
    phone: "(519) 966-6500",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Windsor's main GM point. Good local service.",
  },

  // ══════════════════ HYUNDAI ══════════════════
  {
    id: 400, make: "hyundai",
    name: "Toronto Hyundai",
    city: "Toronto", region: "toronto-gta", size: "large",
    website: "https://www.torontohyundai.com",
    phone: "(416) 769-9000",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Large Toronto Hyundai dealer. Tucson, Santa Fe, Palisade stock.",
  },
  {
    id: 401, make: "hyundai",
    name: "Erin Mills Hyundai",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.erinmillshyundai.com",
    phone: "(905) 820-6440",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "Top GTA volume dealer with wide inventory.",
  },
  {
    id: 402, make: "hyundai",
    name: "Brampton Hyundai",
    city: "Brampton", region: "toronto-gta", size: "large",
    website: "https://www.bramptonhyundai.com",
    phone: "(905) 846-8868",
    hasZeroPercent: false, islamicFriendly: true,
    notes: "High-traffic location serving Brampton's large Muslim community.",
  },
  {
    id: 403, make: "hyundai",
    name: "Windsor Hyundai",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.windsorhyundai.ca",
    phone: "(519) 966-2100",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Windsor's Hyundai option. Good on Tucson & Elantra.",
  },
  {
    id: 404, make: "hyundai",
    name: "Barrie Hyundai",
    city: "Barrie", region: "barrie", size: "medium",
    website: "https://www.barriehyundai.com",
    phone: "(705) 726-7900",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Serves Simcoe County region.",
  },

  // ══════════════════ KIA ══════════════════
  {
    id: 500, make: "kia",
    name: "Kia of Brampton",
    city: "Brampton", region: "toronto-gta", size: "large",
    website: "https://www.kiaofbrampton.ca",
    phone: "(905) 451-5222",
    hasZeroPercent: true, islamicFriendly: true,
    notes: "One of GTA's highest-volume Kia points. Telluride & Sorento in stock.",
  },
  {
    id: 501, make: "kia",
    name: "Mississauga Kia",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.mississaugakia.com",
    phone: "(905) 615-9777",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Large lot, competitive on Telluride and Sportage.",
  },
  {
    id: 502, make: "kia",
    name: "Toronto Kia",
    city: "Toronto", region: "toronto-gta", size: "medium",
    website: "https://www.torontokia.com",
    phone: "(416) 239-6789",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Central Toronto location with certified used options.",
  },
  {
    id: 503, make: "kia",
    name: "Windsor Kia",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.windsorkia.ca",
    phone: "(519) 966-8400",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Local Windsor Kia dealer.",
  },

  // ══════════════════ NISSAN ══════════════════
  {
    id: 600, make: "nissan",
    name: "Oakville Nissan",
    city: "Oakville", region: "toronto-gta", size: "large",
    website: "https://www.oakvillenissan.ca",
    phone: "(905) 842-3939",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Top Nissan dealer in west GTA. Pathfinder, Frontier, Armada.",
  },
  {
    id: 601, make: "nissan",
    name: "Erin Park Nissan",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.erinparknissan.com",
    phone: "(905) 822-2000",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Large GTA inventory. Known for strong lease deals.",
  },
  {
    id: 602, make: "nissan",
    name: "Brampton Nissan",
    city: "Brampton", region: "toronto-gta", size: "large",
    website: "https://www.bramptonnissan.ca",
    phone: "(905) 458-1900",
    hasZeroPercent: false, islamicFriendly: true,
    notes: "Active dealer in Brampton's Muslim community.",
  },
  {
    id: 603, make: "nissan",
    name: "Windsor Nissan",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.windsornissan.ca",
    phone: "(519) 948-1400",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Windsor's main Nissan point.",
  },

  // ══════════════════ SUBARU ══════════════════
  {
    id: 700, make: "subaru",
    name: "Subaru of Mississauga",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.subaruofmississauga.com",
    phone: "(905) 270-4555",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Highest-volume Subaru dealer in Ontario. Outback, Forester, WRX.",
  },
  {
    id: 701, make: "subaru",
    name: "Downtown Subaru",
    city: "Toronto", region: "toronto-gta", size: "large",
    website: "https://www.downtownsubaru.com",
    phone: "(416) 588-0777",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Popular urban dealer. Strong on certified pre-owned.",
  },
  {
    id: 702, make: "subaru",
    name: "Subaru of Windsor",
    city: "Windsor", region: "windsor", size: "medium",
    website: "https://www.subaruwindsor.com",
    phone: "(519) 944-1000",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Windsor's Subaru option.",
  },

  // ══════════════════ JEEP ══════════════════
  {
    id: 800, make: "jeep",
    name: "Meadowvale Chrysler Jeep",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.meadowvalechrysler.com",
    phone: "(905) 567-2277",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Large GTA Stellantis dealer. Wrangler 4xe (hybrid) stocked.",
  },
  {
    id: 801, make: "jeep",
    name: "Northway Chrysler Jeep Dodge",
    city: "Barrie", region: "barrie", size: "large",
    website: "https://www.northwaychrysler.com",
    phone: "(705) 739-9600",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Wrangler & Gladiator inventory. Strong lease deals.",
  },
  {
    id: 802, make: "jeep",
    name: "Westwood Chrysler Jeep Dodge Ram",
    city: "Windsor", region: "windsor", size: "large",
    website: "https://www.westwoodauto.ca",
    phone: "(519) 944-4000",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Windsor's main Stellantis dealer. Good on Wrangler deals.",
  },
  {
    id: 803, make: "jeep",
    name: "Brampton Chrysler",
    city: "Brampton", region: "toronto-gta", size: "medium",
    website: "https://www.bramptonchrysler.com",
    phone: "(905) 450-5500",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Active Brampton Stellantis group.",
  },

  // ══════════════════ RAM ══════════════════
  {
    id: 900, make: "ram",
    name: "Meadowvale Chrysler Dodge Ram",
    city: "Mississauga", region: "toronto-gta", size: "large",
    website: "https://www.meadowvalechrysler.com",
    phone: "(905) 567-2277",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "GTA's largest Ram inventory. Commercial fleet options.",
  },
  {
    id: 901, make: "ram",
    name: "Northway Chrysler Jeep Dodge Ram",
    city: "Barrie", region: "barrie", size: "large",
    website: "https://www.northwaychrysler.com",
    phone: "(705) 739-9600",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Ram TRX and 1500 TRX available. Popular with truck buyers.",
  },
  {
    id: 902, make: "ram",
    name: "Westwood Chrysler Dodge Ram",
    city: "Windsor", region: "windsor", size: "large",
    website: "https://www.westwoodauto.ca",
    phone: "(519) 944-4000",
    hasZeroPercent: true, islamicFriendly: false,
    notes: "Strong Ram 1500 & 2500 inventory in Windsor.",
  },
  {
    id: 903, make: "ram",
    name: "Brampton Chrysler Dodge Ram",
    city: "Brampton", region: "toronto-gta", size: "medium",
    website: "https://www.bramptonchrysler.com",
    phone: "(905) 450-5500",
    hasZeroPercent: false, islamicFriendly: false,
    notes: "Brampton area Ram dealer.",
  },
];
